# This config file stores credentials and other sensitive information.
# DO NOT commit this file to version control.
# 
# To use substitution in your great_expectations.yml file, use the following syntax:
#   my_key: ${my_value}
#   my_key: $my_value
#
# Environment variables take precedence over values defined here.
#
# For more information, see: https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials

MYSQL_CONNECTION_STRING: mysql+pymysql://admin:adminpwrd@de-c2w3a1-rds.c1kkgcw4ktts.us-east-1.rds.amazonaws.com:3306/taxi_trips
